### ISSUE TITLE
The Sparse4Mix and Sparse5Mix metadata

### ISSUE THREAD

**Issue by tsian077** [fjiang9/sanet#1]
hi! , thank you so much for your work, I have read your paper, and I am interested in your Sparse4Mix and Sparse5Mix metadata JSON file, can I get it from you? Thank you very much.

**Comment by fjiang9** [comment]
@tsian077 Hi, thanks for your interest. I've just uploaded the JSON files for generating Sparse4Mix and Sparse5Mix to the [SparseLibriMix repository](https://github.com/fjiang9/SparseLibriMix).

**Comment by tsian077** [comment]
Thanks, It helps me a lot, again, Thank you for your great work. 👍🏻
